# Generated by Django 5.0.2 on 2025-05-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_choice', models.CharField(choices=[('1', '₦50,000'), ('2', '₦100,000'), ('3', '₦1,000,000')], default='1', max_length=25)),
                ('withdrawl', models.DecimalField(decimal_places=16, max_digits=32)),
                ('deposit', models.DecimalField(decimal_places=16, max_digits=32)),
                ('balance', models.DecimalField(decimal_places=16, max_digits=32)),
            ],
        ),
    ]
