# Generated by Django 5.0.2 on 2025-05-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='balance',
            new_name='maximum_balance',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='deposit',
            new_name='minimum_balance',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='withdrawl',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='tier_choice',
            field=models.CharField(choices=[('1', 'Tier 1'), ('2', 'Tier 2'), ('3', 'Tier 3')], default='1', max_length=25),
        ),
    ]
