# Generated by Django 5.0.2 on 2025-05-06 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_balance_dashboard_maximum_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierAmountDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_choice', models.CharField(choices=[('1', 'Tier 1'), ('2', 'Tier 2'), ('3', 'Tier 3')], default='1', max_length=25)),
                ('minimum_balance', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50000), django.core.validators.MaxValueValidator(100000)])),
                ('maximum_balance', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(1000000)])),
            ],
        ),
        migrations.DeleteModel(
            name='DashBoard',
        ),
    ]
