# Generated by Django 5.0.2 on 2025-05-06 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tieramountdb_delete_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='tieramountdb',
            name='medium_balance',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50000), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='tieramountdb',
            name='minimum_balance',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50000)]),
        ),
    ]
