# Generated by Django 5.0.2 on 2025-05-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_tieramountdb_medium_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tieramountdb',
            name='maximum_balance',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='tieramountdb',
            name='minimum_balance',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=32, null=True),
        ),
    ]
